version: '3'
services:
  galera1:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm://galera1,galera2,galera3 --wsrep-new-cluster
    hostname: galera1
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    ports:
    - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == default]
  galera2:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm://galera1,galera2,galera3
    hostname: galera2
    ports:
    - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == swarm-1]
      restart_policy:
        condition: on-failure
        delay: 10s 
  galera3:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm://galera1,galera2,galera3
    hostname: galera3
    ports:
    - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == swarm-2] 
      restart_policy:
        condition: on-failure
        delay: 10s
  visualizer:
    image: manomarks/visualizer
    ports:
    - "8080:8080"
    #stop_grace_period: 1m30s
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.hostname == default]
volumes:
  db-data:
